- name: Preparing to install Composer
  file:
    path: "{{ansible_env.HOME}}/bin"
    recurse: yes
    state: directory
- name: Downloading Composer
  get_url:
    url: https://raw.githubusercontent.com/composer/getcomposer.org/0f5ad9cc03286327b33cfea888904256576da4ce/web/installer
    dest: /tmp/composer-setup.php
- name: Installing Composer
  command: php /tmp/composer-setup.php --quiet --install-dir={{ansible_env.HOME}}/bin --filename=composer
