- name: Installing DOSBox Staging
  become: yes
  dnf:
    name: dosbox-staging
    state: latest
- name: Preparing to configure DOSBox Staging
  command: dosbox -printconf
  register: dosbox_conf
- name: Configuring DOSBox Staging
  ini_file:
    path: "{{dosbox_conf.stdout}}"
    section: "{{item.key.split('.')[0]}}"
    option: "{{item.key.split('.')[1]}}"
    value: "{{item.value}}"
  with_dict: "{{dosbox_options}}"
- name: Preparing to configure DOSBox Staging autoexec
  file:
    path: "{{ansible_env.HOME}}/dosbox"
    state: directory
- name: Configuring DOSBox Staging autoexec
  blockinfile:
    path: "{{dosbox_conf.stdout}}"
    marker: "# {mark} AUTOEXEC BLOCK"
    insertafter: "# You can put your MOUNT lines here."
    block: |
      @MOUNT C ~/dosbox
      @C:
