- name: Preparing to configure SELinux for DOSBox
  command: getenforce
  register: sestatus
- name: Configuring SELinux for DOSBox
  become: yes
  seboolean:
    name: selinuxuser_execheap
    state: yes
    persistent: yes
  when: '"Enforcing" in sestatus.stdout'
- name: Installing DOSBox
  become: yes
  dnf:
    name: dosbox
    state: latest
- name: Preparing to configure DOSBox
  command: dosbox -printconf
  register: dosbox_conf
- name: Configuring DOSBox
  ini_file:
    path: "{{dosbox_conf.stdout}}"
    section: "{{item.key.split('.')[0]}}"
    option: "{{item.key.split('.')[1]}}"
    value: "{{item.value}}"
    no_extra_spaces: yes
  with_dict: "{{dosbox_options}}"
- name: Preparing to configure DOSBox autoexec
  file:
    path: "{{ansible_env.HOME}}/dosbox"
    state: directory
- name: Configuring DOSBox autoexec
  blockinfile:
    path: "{{dosbox_conf.stdout}}"
    marker: "# {mark} AUTOEXEC BLOCK"
    insertafter: "# You can put your MOUNT lines here."
    block: |
      MOUNT C ~/dosbox
      C:
