- name: Adding flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
- name: Installing flatpaks from flathub
  flatpak:
    name: "{{item}}"
    state: present
    remote: flathub
  loop: "{{flathub}}"
