- name: Preparing to install fonts
  file:
    path: "{{ansible_env.HOME}}/.local/share/fonts"
    recurse: yes
    state: directory
- name: Installing Microsoft fonts
  become: yes
  dnf:
    name:
      - cabextract
      - 'https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm'
    state: latest
    disable_gpg_check: yes
- name: Installing Fira Code fonts
  get_url:
    url: https://github.com/tonsky/FiraCode/blob/master/distr/ttf/FiraCode-{{item}}.ttf?raw=true
    dest: "{{ansible_env.HOME}}/.local/share/fonts"
  loop:
    - Bold
    - Light
    - Medium
    - Regular
    - Retina
- name: Downloading Cascadia Code fonts
  get_url:
    url: https://github.com/microsoft/cascadia-code/releases/download/v2009.22/CascadiaCode-2009.22.zip
    dest: /tmp/CascadiaCode-2009.22.zip
- name: Installing Cascadia Code fonts
  shell: unzip -jo /tmp/CascadiaCode-2009.22.zip ttf/*.ttf -d ~/.local/share/fonts
  args:
    warn: false
- name: Updating font cache
  command: fc-cache -f

