- name: Enabling Google Chrome repository
  become: yes
  ini_file:
    path: /etc/yum.repos.d/google-chrome.repo
    section: google-chrome
    option: enabled
    value: "1"
    no_extra_spaces: yes
- name: Installing Google Chrome
  become: yes
  dnf:
    name: google-chrome-stable
    state: latest
