- name: Importing Google Chrome GPG key
  become: yes
  rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
    state: present
- name: Adding Google Chrome repository
  become: yes
  yum_repository:
    name: google-chrome
    description: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
- name: Installing Google Chrome
  become: yes
  dnf:
    name: google-chrome-stable
    state: latest

