- name: Importing Microsoft Edge GPG key
  become: yes
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
- name: Adding Microsoft Edge repository
  become: yes
  yum_repository:
    name: microsoft-edge-dev
    description: microsoft-edge-dev
    baseurl: https://packages.microsoft.com/yumrepos/edge/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
- name: Installing Microsoft Edge
  become: yes
  dnf:
    name: microsoft-edge-dev
    state: latest
