- name: Installing Powerline
  become: yes
  dnf:
    name: powerline,powerline-fonts
    state: latest
- name: Installing Powerline Gitstatus
  become: yes
  pip:
    name: powerline-gitstatus
- name: Preparing to configure Powerline
  file:
    path: "{{ansible_env.HOME}}/.config/powerline/{{item}}"
    recurse: yes
    state: directory
  with_items:
    - themes/shell
    - colorschemes
- name: Configuring Powerline color scheme
  copy:
    src: "{{playbook_dir}}/../data/powerline-colorscheme.json"
    dest: "{{ansible_env.HOME}}/.config/powerline/colorschemes/default.json"
- name: Configuring Powerline shell theme
  copy:
    src: "{{playbook_dir}}/../data/powerline-shell-theme.json"
    dest: "{{ansible_env.HOME}}/.config/powerline/themes/shell/default_leftonly.json"
- name: Configuring Powerline
  copy:
    src: "{{playbook_dir}}/../data/powerline-config.json"
    dest: "{{ansible_env.HOME}}/.config/powerline/config.json"
- name: Configuring bash for Powerline
  blockinfile:
    path: "{{ansible_env.HOME}}/.bashrc"
    create: yes
    marker: "# {mark} POWERLINE BLOCK"
    block: |
      if [ -f `which powerline-daemon` ]; then
        powerline-daemon -q
        POWERLINE_BASH_CONTINUATION=1
        POWERLINE_BASH_SELECT=1
        . /usr/share/powerline/bash/powerline.sh
      fi
