- name: Preparing to install VirtualBox
  become: yes
  dnf:
    name: kernel-devel
    state: latest
- name: Downloading VirtualBox
  get_url:
    url: https://download.virtualbox.org/virtualbox/6.1.18/VirtualBox-6.1.18-142142-Linux_amd64.run
    dest: "/tmp"
- name: Preparing VirualBox installer
  file: dest="/tmp/VirtualBox-6.1.18-142142-Linux_amd64.run" mode=a+x
- name: Installing VirtualBox
  become: yes
  shell: /tmp/VirtualBox-6.1.18-142142-Linux_amd64.run --nox11
