- name: Importing Visual Studio Code GPG key
  become: yes
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
- name: Adding Visual Studio Code repository
  become: yes
  shell: 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
- name: Installing Visual Studio Code
  become: yes
  dnf:
    name: code
    state: latest
