- name: Prepare to install fonts
  file:
    path: "{{ansible_env.HOME}}/.local/share/fonts"
    recurse: yes
    state: directory
- name: Install Microsoft fonts
  become: yes
  dnf:
    name:
      - cabextract
      - 'https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm'
    state: latest
  when: microsoft_fonts.install
- name: Install Fira Code fonts
  get_url:
    url: https://github.com/tonsky/FiraCode/blob/master/distr/ttf/FiraCode-{{item}}.ttf?raw=true
    dest: "{{ansible_env.HOME}}/.local/share/fonts"
  loop:
    - Bold
    - Light
    - Medium
    - Regular
    - Retina
  when: fira_code_fonts.install or (vscode.install and vscode.configure)
- name: Update font cache
  command: fc-cache -f
