- name: Install gThumb
  become: yes
  dnf:
    name: gthumb
    state: latest
- include: dconf.yaml name="{{'Enable' if item.value == 'boolean true' else ('Disable' if item.value == 'boolean false' else 'Set')}} {{item.name}} for gThumb" key={{item.key}} value={{item.value}}
  loop: "{{gthumb.config}}"
  when: gthumb.configure
