- name: Install MariaDB
  become: yes
  dnf:
    name: mariadb-server
    state: latest
- name: Enable and start MariaDB Server
  become: yes
  service:
    name: mariadb
    enabled: yes
    state: started
  when: mariadb.enable
