- name: Install RPM Fusion free repository
  become: yes
  dnf:
    name: 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_lsb.major_release}}.noarch.rpm'
    state: present
- name: Install RPM Fusion nonfree repository
  become: yes
  dnf:
    name: 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_lsb.major_release}}.noarch.rpm'
    state: present
