- name: Prepare to install Typora
  file:
    path: "{{ansible_env.HOME}}/{{item}}"
    recurse: yes
    state: directory
  loop:
    - bin
    - .local/share/applications
- name: Install Typora
  unarchive:
    src: "https://typora.io/linux/Typora-linux-x64.tar.gz"
    remote_src: yes
    dest: "{{ansible_env.HOME}}/bin"
- name: Add Typora to applications
  copy:
    dest: "{{ansible_env.HOME}}/.local/share/applications/typora.desktop"
    content: |
      [Desktop Entry]
      Encoding=UTF-8
      Name=Typora
      Exec={{ansible_env.HOME}}/bin/Typora-linux-x64/Typora
      Icon={{ansible_env.HOME}}/bin/Typora-linux-x64/resources/app/asserts/icon/icon_512x512.png
      Type=Application
      Categories=Office;Development;
