- name: Import Visual Studio Code GPG key
  become: yes
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
- name: Add Visual Studio Code repository
  become: yes
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
- name: Install Visual Studio Code
  become: yes
  dnf:
    name: code
    state: latest
- name: Install Visual Studio Code extensions
  command: code --install-extension {{item}}
  loop: "{{vscode.install_extensions}}"
- name: Prepare to configure Visual Studio Code
  file:
    path: "{{ansible_env.HOME}}/.config/Code/User"
    recurse: yes
    state: directory
  when: vscode.configure
- name: Configure Visual Studio Code
  copy:
    src: "{{playbook_dir}}/../data/code-user-settings.json"
    dest: "{{ansible_env.HOME}}/.config/Code/User/settings.json"
  when: vscode.configure
