- hosts: localhost
  vars:
    packages:
      - gstreamer1-plugins-good-extras,gstreamer1-plugins-ugly,gstreamer1-plugins-bad-freeworld,gstreamer1-plugins-bad-free
      - php,php-mysqlnd,php-gd,php-mbstring,php-json
      - mariadb-server
      - nodejs
      - golang
      - inkscape
      - mediawriter
      - lm_sensors
      - unrar
      - mkvtoolnix
      - gnome-subtitles
      - gnome-tweaks
      - mc
      - easytag
      - soundconverter
      - vlc
      - transmission
      - gthumb
      - celluloid
      - tilix
    flathub:
      - com.getpostman.Postman
      - com.github.johnfactotum.Foliate
      - com.rafaelmardojai.Blanket
      - com.rawtherapee.RawTherapee
      - com.slack.Slack
      - com.spotify.Client
      - com.viber.Viber
      - de.haeckerfelix.Shortwave
      - io.lmms.LMMS
      - no.mifi.losslesscut
      - org.audacityteam.Audacity
      - org.blender.Blender
      - org.darktable.Darktable
      - org.fontforge.FontForge
      - org.gimp.GIMP
      - org.gnome.FontManager
      - org.gnome.Lollypop
      - org.gnome.Podcasts
      - org.gnome.SoundRecorder
      - org.kde.kdenlive
      - org.kde.krita
      - org.mypaint.MyPaint
      - org.stellarium.Stellarium
      - uk.co.mrbenshef.Boop-GTK
    gnome_shell_extensions:
      - dash-to-panel@jderose9.github.com
      - appindicatorsupport@rgcjonas.gmail.com
    vscode_extensions:
      - formulahendry.auto-close-tag
      - coenraads.bracket-pair-colorizer-2
      - equinusocio.vsc-material-theme
      - editorconfig.editorconfig
      - github.github-vscode-theme
      - eamodio.gitlens
      - golang.go
      - paulhocker.kick-assembler-vscode-ext
      - runem.lit-plugin
      - dawhite.mustache
      - felixfbecker.php-debug
      - bmewburn.vscode-intelephense-client
      - ms-python.python
    dconf:
      # GNOME
      - key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
        value: boolean true
      - key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
        value: uint32 5250
      - key: /org/gnome/desktop/input-sources/sources
        value: "[('xkb', 'us'), ('xkb', 'rs+latin'), ('xkb', 'rs')]"
      - key: /system/locale/region
        value: "'en_GB.UTF-8'"
      # Terminal
      - key: /org/gnome/terminal/legacy/default-show-menubar
        value: boolean false
      - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-columns
        value: 160
      - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-rows
        value: 48
      - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-transparent-background
        value: boolean true
      - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-transparency-percent
        value: 10
      - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollbar-policy
        value: "'never'"
      # Tilix
      - key: /com/gexperts/Tilix/theme-variant
        value: "'dark'"
      - key: /com/gexperts/Tilix/terminal-title-show-when-single
        value: boolean false
      - key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/default-size-columns
        value: 160
      - key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/default-size-rows
        value: 48
      - key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/background-transparency-percent
        value: 10
      - key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/show-scrollbar
        value: boolean false
      # gThumb
      - key: /org/gnome/gthumb/browser/thumbnail-size
        value: 200
      # Celluloid
      - key: /io/github/celluloid-player/celluloid/mpv-options
        value: "'--sub-auto=fuzzy --sub-codepage=utf8:cp1250 --sub-text-color=#ffff99 --sub-scale=1.5 --ass-style-override=strip'"
      # Videos
      - key: /org/gnome/Totem/autoload-subtitles
        value: boolean true
      - key: /org/gnome/Totem/subtitle-encoding
        value: "'WINDOWS-1250'"
    dosbox_options:
      - sdl.fullscreen: 'true'
      - sdl.fulldouble: 'true'
      - sdl.fullresolution: 'desktop'
      - sdl.windowresolution: 'original'
      - sdl.output: 'opengl'
    services:
      - httpd
      - mariadb
  tasks:
    - include: tasks/update.yaml
    - include: tasks/rpm-fusion.yaml
    - include: tasks/packages.yaml
    - include: tasks/flathub.yaml
    - include: tasks/google-chrome.yaml
    - include: tasks/fonts.yaml
    - include: tasks/skype.yaml
    - include: tasks/yarn.yaml
    - include: tasks/gnome-shell-extensions.yaml
    - include: tasks/vscode.yaml
    - include: tasks/composer.yaml
    - include: tasks/dconf.yaml
    - include: tasks/dosbox.yaml
    - include: tasks/processing.yaml version=3.5.4
    - include: tasks/typora.yaml
    - include: tasks/services.yaml
    - include: tasks/powerline.yaml
