- hosts: localhost
  vars:
    packages:
      - akmod-nvidia,xorg-x11-drv-nvidia-cuda # NVIDIA Drivers
      - "@multimedia,gstreamer1-plugins-good-extras,gstreamer1-plugin-libav,gstreamer1-plugin-openh264" # Multimedia
      - fira-code-fonts,cascadia-fonts-all # Fonts
      - google-chrome-stable # Google Chrome
      - php,php-mysqlnd,php-gd,php-mbstring,php-json,php-xml,php-pecl-imagick,php-pecl-zip,php-soap,php-tidy # PHP
      - mariadb-server # MariaDB Server
      - nodejs # Node.js
      - rust,cargo # Rust
      - inkscape # Inkscape
      - gnome-sound-recorder # Sound Recorder
      - tilix # Tilix
      - vlc # VLC media player
      - gnome-tweaks # Tweaks
      - transmission # Transmission
      - easytag # EasyTAG
      - gnome-subtitles # Gnome Subtitles
      - soundconverter # Sound Converter
      - vice # VICE
      - steam # Steam
      - celluloid # Celluloid
      - gnome-extensions-app # Extensions
      - gthumb # gThumb
      - mkvtoolnix # MKVToolNix GUI
      - audacity-freeworld # Audacity
      - dconf-editor # dconf Editor
      - lm_sensors,unrar,mc # Utilities
      - libadwaita-devel # Development files
      - libappindicator # GNOME Shell extensions dependencies
    packages_nogpgcheck:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_lsb.major_release}}.noarch.rpm # RPM Fusion free
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_lsb.major_release}}.noarch.rpm # RPM Fusion nonfree
      - https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-8.0.31-1.fc37.x86_64.rpm # MySQL Workbench
      - https://linux.dropbox.com/packages/fedora/nautilus-dropbox-2022.12.05-1.fedora.x86_64.rpm # Dropbox
      - https://code-industry.net/public/master-pdf-editor-4.3.89_qt5.x86_64.rpm # Master PDF Editor 4
    flathub:
      - com.spotify.Client # Spotify
      - com.getpostman.Postman # Postman
      - io.github.lainsce.Khronos # Khronos
      - im.riot.Riot # Element
      - com.github.tchx84.Flatseal # Flatseal
      - com.viber.Viber # Viber
      - com.github.geigi.cozy # Cozy
      - com.github.huluti.Curtail # Curtail
      - com.github.johnfactotum.Foliate # Foliate
      - com.github.liferooter.textpieces # Text Pieces
      - com.github.marktext.marktext # MarkText
      - com.github.rafostar.Clapper # Clapper
      - com.icons8.Lunacy # Lunacy
      - com.obsproject.Studio # OBS Studio
      - com.rafaelmardojai.Blanket # Blanket
      - com.rafaelmardojai.WebfontKitGenerator # Webfont Kit Generator
      - com.rawtherapee.RawTherapee # RawTherapee
      - com.skype.Client # Skype
      - com.slack.Slack # Slack
      - de.haeckerfelix.Shortwave # Shortwave
      - fr.romainvigier.MetadataCleaner # Metadata Cleaner
      - io.lmms.LMMS # LMMS
      - io.typora.Typora # Typora
      - md.obsidian.Obsidian # Obsidian
      - net.fsuae.FS-UAE # FS-UAE
      - no.mifi.losslesscut # LosslessCut
      - org.blender.Blender # Blender
      - org.cvfosammmm.Setzer # Setzer
      - org.darktable.Darktable # Darktable
      - org.fontforge.FontForge # FontForge
      - org.gaphor.Gaphor # Gaphor
      - org.gimp.GIMP # GNU Image Manipulation Program
      - org.gnome.DejaDup # Déjà Dup Backups
      - org.gnome.Evolution # Evolution
      - org.gnome.FontManager # Font Manager
      - org.gnome.Lollypop # Lollypop
      - org.gnome.Podcasts # Podcasts
      - org.gnome.Solanum # Solanum
      - org.gnome.design.IconLibrary # Icon Library
      - org.gustavoperedo.FontDownloader # Font Downloader
      - org.kde.kdenlive # Kdenlive
      - org.kde.krita # Krita
      - org.mypaint.MyPaint # MyPaint
      - org.stellarium.Stellarium # Stellarium
    gnome_shell_extensions:
      - dash-to-panel@jderose9.github.com
      - blur-my-shell@aunetx
      - bluetooth-quick-connect@bjarosze.gmail.com
      - appindicatorsupport@rgcjonas.gmail.com
      - freon@UshakovVasilii_Github.yahoo.com
      - gsconnect@andyholmes.github.io
    dconf:
      # GNOME
      - key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
        value: boolean true
      - key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
        value: uint32 5250
      - key: /org/gnome/desktop/input-sources/sources
        value: "[('xkb', 'us'), ('xkb', 'rs+latin'), ('xkb', 'rs')]"
      - key: /system/locale/region
        value: "'en_GB.UTF-8'"
      - key: /org/gnome/shell/favorite-apps
        value: "['google-chrome.desktop', 'com.spotify.Client.desktop', 'com.getpostman.Postman.desktop', 'io.github.lainsce.Khronos.desktop', 'im.riot.Riot.desktop', 'code.desktop', 'com.gexperts.Tilix.desktop', 'org.gnome.Nautilus.desktop']"
      - key: /org/gnome/desktop/screensaver/lock-enabled
        value: boolean false
      # Terminal
      - key: /org/gnome/terminal/legacy/default-show-menubar
        value: boolean false
      - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-columns
        value: 160
      - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-rows
        value: 48
      - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-transparent-background
        value: boolean true
      - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-transparency-percent
        value: 10
      - key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollbar-policy
        value: "'never'"
      # Tilix
      - key: /com/gexperts/Tilix/theme-variant
        value: "'dark'"
      - key: /com/gexperts/Tilix/terminal-title-show-when-single
        value: boolean false
      - key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/default-size-columns
        value: 160
      - key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/default-size-rows
        value: 48
      - key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/background-transparency-percent
        value: 10
      - key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/show-scrollbar
        value: boolean false
      # gThumb
      - key: /org/gnome/gthumb/browser/thumbnail-size
        value: 200
      # Celluloid
      - key: /io/github/celluloid-player/celluloid/mpv-options
        value: "'--sub-auto=fuzzy --sub-codepage=utf8:cp1250 --sub-text-color=#ffff99 --sub-scale=1.5 --ass-style-override=strip'"
      # Videos
      - key: /org/gnome/Totem/autoload-subtitles
        value: boolean true
      - key: /org/gnome/Totem/subtitle-encoding
        value: "'WINDOWS-1250'"
      # GNOME Shell extensions
      - key: /org/gnome/shell/extensions/dash-to-panel/panel-element-positions
        value: "'{\"0\":[{\"element\":\"showAppsButton\",\"visible\":true,\"position\":\"stackedBR\"},{\"element\":\"activitiesButton\",\"visible\":false,\"position\":\"stackedTL\"},{\"element\":\"leftBox\",\"visible\":true,\"position\":\"stackedTL\"},{\"element\":\"taskbar\",\"visible\":true,\"position\":\"centerMonitor\"},{\"element\":\"centerBox\",\"visible\":true,\"position\":\"stackedBR\"},{\"element\":\"rightBox\",\"visible\":true,\"position\":\"stackedBR\"},{\"element\":\"dateMenu\",\"visible\":true,\"position\":\"stackedBR\"},{\"element\":\"systemMenu\",\"visible\":true,\"position\":\"stackedBR\"},{\"element\":\"desktopButton\",\"visible\":true,\"position\":\"stackedBR\"}]}'"
      - key: /org/gnome/shell/extensions/dash-to-panel/appicon-margin
        value: 4
      - key: /org/gnome/shell/extensions/dash-to-panel/trans-use-custom-opacity
        value: boolean true
    dosbox_options:
      - sdl.fullscreen: 'true'
    services:
      - httpd
      - mariadb
  tasks:
    - include_tasks: tasks/packages-nogpgcheck.yaml
    - include_tasks: tasks/packages.yaml
    - include_tasks: tasks/flathub.yaml
    - include_tasks: tasks/microsoft-fonts.yaml
    - include_tasks: tasks/yarn.yaml
    - include_tasks: tasks/gnome-shell-extensions.yaml
    - include_tasks: tasks/vscode.yaml
    - include_tasks: tasks/composer.yaml
    - include_tasks: tasks/dosbox.yaml
    - include_tasks: tasks/services.yaml
    - include_tasks: tasks/powerline.yaml
    - include_tasks: tasks/microsoft-edge.yaml
    - include_tasks: tasks/virtualbox.yaml
    - include_tasks: tasks/aseprite.yaml
    - include_tasks: tasks/kick-assembler.yaml
    - include_tasks: tasks/c64-65xe-nes-debugger.yaml
    - include_tasks: tasks/open-razer.yaml
    - include_tasks: tasks/charm.yaml
    - include_tasks: tasks/processing.yaml
    - include_tasks: tasks/dconf.yaml
