- hosts: localhost
  tasks:
    - name: Install RPM Fusion free repository
      become: yes
      dnf:
        name: 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_lsb.major_release}}.noarch.rpm'
        state: present
    - name: Install RPM Fusion nonfree repository
      become: yes
      dnf:
        name: 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_lsb.major_release}}.noarch.rpm'
        state: present
    - name: Install Yarn repository
      become: yes
      get_url:
        url: https://dl.yarnpkg.com/rpm/yarn.repo
        dest: /etc/yum.repos.d/yarn.repo
    - name: Import Google Chrome GPG key
      become: yes
      rpm_key:
        key: https://dl.google.com/linux/linux_signing_key.pub
        state: present
    - name: Add Google Chrome repository
      become: yes
      yum_repository:
        name: google-chrome
        description: google-chrome
        baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
        gpgcheck: yes
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    - name: Import Visual Studio Code GPG key
      become: yes
      rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present
    - name: Add Visual Studio Code repository
      become: yes
      yum_repository:
        name: code
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    - name: Update all packages
      become: yes
      dnf:
        name: '*'
        state: latest
    - name: Install GStreamer plugins
      become: yes
      dnf:
        name: gstreamer-plugins-bad,gstreamer-plugins-good,gstreamer-plugins-ugly,gstreamer-plugins-bad-free,gstreamer-plugins-good-extras,gstreamer-plugins-bad-nonfree,gstreamer-plugins-bad-free-extras,gstreamer1-plugins-ugly,gstreamer1-plugins-good-extras,gstreamer1-plugins-bad-nonfree,gstreamer1-plugins-bad-freeworld,gstreamer1-plugins-bad-free-extras
        state: latest
    - name: Install Google Chrome
      become: yes
      dnf:
        name: google-chrome-stable
        state: latest
    - name: Install Visual Studio Code
      become: yes
      dnf:
        name: code
        state: latest
    - name: Install PHP
      become: yes
      dnf:
        name: php,php-mysqlnd,php-gd,php-mbstring
        state: latest
    - name: Enable and restart Apache HTTP Server
      become: yes
      service:
        name: httpd
        enabled: yes
        state: restarted
    - name: Install MariaDB
      become: yes
      dnf:
        name: mariadb-server
        state: latest
    - name: Enable and start MariaDB Server
      become: yes
      service:
        name: mariadb
        enabled: yes
        state: started
    - name: Install Yarn
      become: yes
      dnf:
        name: yarn
        state: latest
    - name: Install Microsoft fonts
      become: yes
      dnf:
        name:
          - cabextract
          - 'https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm'
        state: latest
    - name: Prepare to install fonts
      file:
        path: "{{ansible_env.HOME}}/.local/share/fonts"
        recurse: yes
        state: directory
    - name: Install Fira Code fonts
      get_url:
        url: https://github.com/tonsky/FiraCode/blob/master/distr/ttf/FiraCode-{{item}}.ttf?raw=true
        dest: "{{ansible_env.HOME}}/.local/share/fonts"
      with_items:
        - Bold
        - Light
        - Medium
        - Regular
        - Retina
    - name: Update font cache
      command: fc-cache -f
    - name: Install Node.js
      become: yes
      dnf:
        name: nodejs
        state: latest
    - name: Install Bower
      become: yes
      npm:
        name: bower
        global: yes
    - name: Install Polymer CLI
      become: yes
      command: npm install -g --unsafe-perm polymer-cli
    - name: Install TypeScript
      become: yes
      npm:
        name: typescript
        global: yes
    - name: Add Flathub flatpak repository
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user
    - name: Install Lollypop from Flathub
      flatpak:
        name: org.gnome.Lollypop
        state: present
        remote: flathub
        method: user
    - name: Install GIMP from Flathub
      flatpak:
        name: org.gimp.GIMP
        state: present
        remote: flathub
        method: user
    - name: Install MyPaint from Flathub
      flatpak:
        name: org.mypaint.MyPaint
        state: present
        remote: flathub
        method: user
    - name: Install Viber from Flathub
      flatpak:
        name: com.viber.Viber
        state: present
        remote: flathub
        method: user
    - name: Enable night light
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
        value: boolean true
    - name: Set night light temperature
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
        value: uint32 5250
    - name: Set input sources
      dconf:
        key: /org/gnome/desktop/input-sources/sources
        value: "[('xkb', 'us'), ('xkb', 'rs+latin'), ('xkb', 'rs'), ('ibus', 'typing-booster')]"
    - name: Set formats
      dconf:
        key: /system/locale/region
        value: "'en_GB.UTF-8'"
